### ISSUE TITLE
v3 : css embeded theme resources are not published

### ISSUE THREAD

**Issue by remyma** [pyrocms/pyrocms#3459]
I don't know if it's a bug or if there is a workaround for this.
I have a custom theme with a css which includes font-face relative resources (fonts, ...)

```css
@font-face {
  font-family: 'Lato';
  src: url('../fonts/lato/lato-black.eot');
  src: url('../fonts/lato/lato-black.eot?#iefix') format('embedded-opentype'), url('../fonts/lato/lato-black.woff') format('woff'), url('../fonts/lato/lato-black.ttf') format('truetype'), url('../fonts/lato/lato-black.svg#latoblack') format('svg');
  font-weight: 900;
  font-style: normal;
}
```

my css files are published in public/assets/default folder, but not font-face resources which then results in 404.
