### ISSUE TITLE
[pyrocms-site] Broken markup at the main page

### ISSUE THREAD

**Issue by Piterden** [pyrocms/pyrocms#4583]
The `iframe` at the bottom of the main page brakes markup.

![image](https://user-images.githubusercontent.com/5930429/30455903-4f2af22a-99aa-11e7-9460-9af716aa31e3.png)

See the white line at the bottom?
This CSS is solving this issue:
```css
[name="google_conversion_frame"] {
    position: absolute;
    bottom: 0;
}
```
