### ISSUE TITLE
Performance Concerns

### ISSUE THREAD

**Issue by Pixney-William** [pyrocms/pyrocms#4694]
I am opening this since the last one was closed. Speed is very important and would like to know / discuss where we are with the plans to improve the results mentioned in the thread below. And also to see if others have better results than myself at 300ms.

If we are still at 300ms, when can we expect these to drop? And maybe a question is if it is possible?

https://github.com/pyrocms/pyrocms/issues/4273

**Comment by Piterden** [comment]
Haha. Why didn't me get it earlier? Now, if Ryan will close something, I will just open the new one!!!

**Comment by bluesaga2001** [comment]
I got the same problem.
I installed Pyrocms 3.4 through composer, when I open the index page ,it takes more than 14s ,and my another laravel project just takes about 500ms on same computer .
In Chrome ,It shows TTFB takes the most time. then I use Xdebug ,I find it access the index.php for 4 times. I have no idea how to continue.

**Comment by immersiontravis** [comment]
@bluesaga2001: What OS is your host machine?

If you're using Homestead (on a non-Windows host), try adding "type: nfs" to your "folders" mapping in Homestead.yaml:

https://pyrocms.com/forum/channels/general/slow-page-loads

https://laracasts.com/discuss/channels/requests/nfs-on-homestead-20

You may also need to install nfs-kernel-server:

sudo apt-get install nfs-kernel-server

The folders section of my Homestead.yaml looks like this:

```
folders:
    - map: ~/Desktop/homesteadsites
      to: /home/vagrant/code
      type: nfs
      options:
          linux__nfs_options: ['async','rw','no_subtree_check','all_squash']

```

This greatly improved load times for me.
